---@alias UIGame { path:string, name: string, icon: string }
---@alias UIGameCategory { name: string, games: UIGame[] }
---@alias UIGameMeta { category?: UIGameCategoryNames, altName?: string, author?: string, createdWithAI?: boolean }
